name: Build image

on:
  push:

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - uses: yeouchien/sanitize-branch-name-action@v1
        id: sanitize
        with:
          branch-name: ${{ github.head_ref || github.ref_name }}

      - name: Publish image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: emilykok/inf2-project-d/backend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.sanitize.outputs.sanitized-branch-name }}
          registry: ghcr.io
          workdir: backend
