name: Build image

on:
  push:

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Publish image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: emilykok/inf2-project-d/backend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ github.head_ref || github.ref_name }}
          registry: ghcr.io